handle correctly attached files that contain spaces
use SMPARSER

diff --git a/bin/upgrade2db3 b/bin/upgrade2db3
--- a/bin/upgrade2db3
+++ b/bin/upgrade2db3
@@ -4,8 +4,10 @@ usage() {
     echo "Usage: upgrade2db3 <src-repo> <dst-repo>"
     echo ""
     echo "Upgrade a v2 smit repository to a v3 format."
+    echo "The environment variable SMPARSER must give the path to smparser."
     exit 1
 }
+
 
 # migrateObject
 # $1 : source file
@@ -30,11 +32,17 @@ migrateObject() {
 
 # main -------------------------------------------------------------------------
 
+
 srcDir=$1
 dstDir=$2
 
 [ -z "$srcDir" ] && usage
 [ -z "$dstDir" ] && usage
+
+if [ ! -x "$SMPARSER" ]; then
+    echo "Error: SMPARSER not defined."
+    usage
+fi
 
 # check that destination dir does not exist
 if [ -e "$dstDir" ]; then
@@ -102,7 +110,32 @@ find "$dstDir" -name project | while read p; do
     # at this moment, the objects are all the entries
     # <sha1>.file.pdf => <sha1>/file.pdf
     find "$pDir/objects" -type f | while read entry; do
-    sed -i -e "/+file/ s; \([0-9a-zA-Z]*\)\.; \1/;g" $entry
+        chmod u+w "$entry"
+        # assume that there is only one +file line
+        n=$(grep "^+file" "$entry" | wc -l)
+        if [ $n -gt 1 ]; then
+            echo "Error: entry $entry has more than one +file"
+            exit 1
+        elif [ $n -eq 1 ]; then
+            # replace the first dot in file references by a slash
+            newFiles=$(mktemp)
+            echo -n "+file" > $newFiles
+            # smparser give this kind of output
+            # smp.1.1 +file
+            # smp.1.2 JV4cgfKVwujvGPsXaEpWTAXnAWo.pic1.png
+            # smp.1.3 JV4cgfKVwujvGPsXaEpWTAXnAWo.pic2.png
+            grep "^+file" "$entry" | $SMPARSER - | grep -v "smp.1.1 +file" | sed -e "s/^smp\.[0-9]*\.[0-9]* //" | while read filename; do
+                newF=$(echo -n $filename | sed -e "s;\.;/;" | $SMPARSER -e)
+                echo -n " $newF" >> $newFiles
+            done
+            newFilesT=$(cat $newFiles)
+            echo -n "oldFiles: "
+            grep "^+file" "$entry"
+            echo "newFilesT: $newFilesT"
+            sed -i -e "/^+file /d" "$entry"
+            echo "$newFilesT" >> "$entry"
+            rm $newFiles # rm temporary file
+        fi
     done
 
     # change files
