code review: migrateFileRefs()

diff --git a/bin/upgrade2db3 b/bin/upgrade2db3
--- a/bin/upgrade2db3
+++ b/bin/upgrade2db3
@@ -33,6 +33,9 @@ migrateObject() {
 # $2 : path to the issue directory
 migrateIssue() {
 
+    local pDir="$1"
+    local issue="$2"
+
     # get the latest entry: ie the one that is not referenced as a parent
     latest=""
     echo "examining issue: $issue..."
@@ -64,6 +67,41 @@ migrateIssue() {
         echo $latest > "$pDir/refs/issues/$issueId"
     fi
 }
+# migrateFileRefs
+# Update the files references in a entry
+# Eg: JV4cgfKVwujvGPsXaEpWTAXnAWo.pic1.png
+#  -> JV4cgfKVwujvGPsXaEpWTAXnAWo/pic1.png
+#                                ^
+# $1 : entry to be updated with the new files references
+migrateFileRefs() {
+    local entry="$1"
+    chmod u+w "$entry"
+    # assume that there is only one +file line
+    n=$(grep "^+file" "$entry" | wc -l)
+    if [ $n -gt 1 ]; then
+        echo "Error: entry $entry has more than one +file"
+        exit 1
+    elif [ $n -eq 1 ]; then
+        # replace the first dot in file references by a slash
+        newFiles=$(mktemp)
+        echo -n "+file" > $newFiles
+        # smparser give this kind of output
+        # smp.1.1 +file
+        # smp.1.2 JV4cgfKVwujvGPsXaEpWTAXnAWo.pic1.png
+        # smp.1.3 JV4cgfKVwujvGPsXaEpWTAXnAWo.pic2.png
+        grep "^+file" "$entry" | $SMPARSER - | grep -v "smp.1.1 +file" | sed -e "s/^smp\.[0-9]*\.[0-9]* //" | while read filename; do
+        newF=$(echo -n $filename | sed -e "s;\.;/;" | $SMPARSER -e)
+        echo -n " $newF" >> $newFiles
+    done
+    newFilesT=$(cat $newFiles)
+    echo -n "oldFiles: "
+    grep "^+file" "$entry"
+    echo "newFilesT: $newFilesT"
+    sed -i -e "/^+file /d" "$entry"
+    echo "$newFilesT" >> "$entry"
+    rm $newFiles # rm temporary file
+fi
+    }
 
 # main -------------------------------------------------------------------------
 
@@ -117,32 +155,8 @@ find "$dstDir" -name project | while read p; do
     # at this moment, the objects are all the entries
     # <sha1>.file.pdf => <sha1>/file.pdf
     find "$pDir/objects" -type f | while read entry; do
-        chmod u+w "$entry"
-        # assume that there is only one +file line
-        n=$(grep "^+file" "$entry" | wc -l)
-        if [ $n -gt 1 ]; then
-            echo "Error: entry $entry has more than one +file"
-            exit 1
-        elif [ $n -eq 1 ]; then
-            # replace the first dot in file references by a slash
-            newFiles=$(mktemp)
-            echo -n "+file" > $newFiles
-            # smparser give this kind of output
-            # smp.1.1 +file
-            # smp.1.2 JV4cgfKVwujvGPsXaEpWTAXnAWo.pic1.png
-            # smp.1.3 JV4cgfKVwujvGPsXaEpWTAXnAWo.pic2.png
-            grep "^+file" "$entry" | $SMPARSER - | grep -v "smp.1.1 +file" | sed -e "s/^smp\.[0-9]*\.[0-9]* //" | while read filename; do
-                newF=$(echo -n $filename | sed -e "s;\.;/;" | $SMPARSER -e)
-                echo -n " $newF" >> $newFiles
-            done
-            newFilesT=$(cat $newFiles)
-            echo -n "oldFiles: "
-            grep "^+file" "$entry"
-            echo "newFilesT: $newFilesT"
-            sed -i -e "/^+file /d" "$entry"
-            echo "$newFilesT" >> "$entry"
-            rm $newFiles # rm temporary file
-        fi
+
+        migrateFileRefs "$entry"
     done
 
     # change files
